apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hkjx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hkjx
    app.kubernetes.io/part-of: tkwch-fix-0075-0001-app
  name: devfile-sample-hkjx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-hkjx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-hkjx
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0001-tenant/tkwch-fix-0075-0001-app/devfile-sample-hkjx@sha256:7d0b1f2ada3af20a9dd741289b501e2db3fad3a36dbd75af7c589ea169c14233
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
